### ISSUE TITLE
2,0 update?

### ISSUE THREAD

**Issue by spidermoose11** [AirBurn0/TooManyPotions#1]
pls pls pls pls pls pls update for game version 2.0. Since the update, this mod no longer works and it's my favorite

Thank you!

**Comment by AirBurn0** [comment]
We are aware of the release of a new version and the current incompatibility, and we definitely plan to support 2.0.0+ versions.

Give me some time...

**Comment by AirBurn0** [comment]
Okie, now it works. You can download the new release from wherever it is more convenient for you.

I added some new items to the item panel, now you can cover yourself in gold cups (yay)!

Unfortunately I don't have time to add more useful features(

**Comment by spidermoose11** [comment]
You guys are awesome! The speed you did this at was downright impressive! I
love your work and I'm excited for when you have the time and means to do
more :)
edit: almost forgot to say thank you! thank you thank you! :}
