### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Jambu2024** [AirBurn0/TooManyPotions#2]
I installed bepinex and this mod but it doesn't work at all in game.

**Comment by AirBurn0** [comment]
> I installed bepinex and this mod but it doesn't work at all in game.

Well, cool for sure, but it works for me.
I'm not a psychic, so I'll ask a couple of guiding questions to figure it out:
1) Does other mods work?
2) Does BepInEx work? You can check if this is or not by running the game, then navigating to the `Potion Craft/BepInEx` folder, and if there is a `LogOutput.log` and it doesn't contain any errors, then it's working.
3) Does mod leave some info in `LogOutput.log` about why it doesn't work?

**Comment by Jambu2024** [comment]
[Message:   BepInEx] BepInEx 5.4.23.2 - Potion Craft (12/20/2024 5:35:21 PM)
[Info   :   BepInEx] Running under Unity v2023.1.13.16771760
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [TooManyPotions 2.0.0]
[Message:   BepInEx] Chainloader startup complete

**Comment by AirBurn0** [comment]
> [Message: BepInEx] BepInEx 5.4.23.2 - Potion Craft (12/20/2024 5:35:21 PM) [Info : BepInEx] Running under Unity v2023.1.13.16771760 [Info : BepInEx] CLR runtime version: 4.0.30319.42000 [Info : BepInEx] Supports SRE: True [Info : BepInEx] System platform: Bits64, Windows [Message: BepInEx] Preloader started [Info : BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.2] [Info : BepInEx] 1 patcher plugin loaded [Info : BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader] [Message: BepInEx] Preloader finished [Message: BepInEx] Chainloader ready [Message: BepInEx] Chainloader started [Info : BepInEx] 1 plugin to load [Info : BepInEx] Loading [TooManyPotions 2.0.0] [Message: BepInEx] Chainloader startup complete

Oh, well, you kinda need another support mod to run this mod.
Consider also installing [ReLocalization](https://github.com/AirBurn0/ReLocalization/releases/tag/1.1.0.1), should be it.
I'll write that in github readme also
